-- Phase 1: Add Super Admin as an additive role.
-- Existing operational roles are intentionally unchanged:
--   1 = Admin, 2 = Sales, 3 = Service, 4 = Sales Manager
-- Super Admin uses 99 to avoid colliding with migrated legacy role lookup ids.

-- Keep a lookup row for administrative clarity. The React app uses users.role_id,
-- not this legacy lookup table, but this makes the role visible in DB reviews.
insert into public.role (id, user_id, role_name, created_at, updated_at)
values (99, 1, 'Super Admin', now(), now())
on conflict (id) do update
set role_name = excluded.role_name,
    updated_at = now();

select setval(
  pg_get_serial_sequence('public.role', 'id'),
  greatest((select max(id) from public.role), 99),
  true
);

create or replace function app_private.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(
    (select role_id = 99 and status <> 'Inactive'
       from public.users
      where id = auth.uid()),
    false
  )
$$;

-- Super Admin should have the same broad operational data access as Admin.
-- Normal Admin remains role_id = 1.
create or replace function app_private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(
    (select role_id in (1, 99) and status <> 'Inactive'
       from public.users
      where id = auth.uid()),
    false
  )
$$;

create or replace function app_private.can_access(p_module text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select app_private.is_admin()
  or coalesce(
    (select mp.can_access
       from public.module_permission mp
      where mp.role_id = app_private.current_role_id()
        and mp.module = p_module
      limit 1),
    false
  )
$$;

-- Normal Admin keeps current user-management ability, but cannot create,
-- update, or delete Super Admin accounts. Super Admin can manage all users.
drop policy if exists users_admin_insert on public.users;
create policy users_admin_insert
on public.users
for insert
to authenticated
with check (
  app_private.is_admin()
  and (app_private.is_super_admin() or role_id <> 99)
);

drop policy if exists users_admin_update on public.users;
create policy users_admin_update
on public.users
for update
to authenticated
using (
  app_private.is_admin()
  and (app_private.is_super_admin() or role_id <> 99)
)
with check (
  app_private.is_admin()
  and (app_private.is_super_admin() or role_id <> 99)
);

drop policy if exists users_admin_delete on public.users;
create policy users_admin_delete
on public.users
for delete
to authenticated
using (
  app_private.is_admin()
  and (app_private.is_super_admin() or role_id <> 99)
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_user_id uuid,
  actor_old_user_id integer,
  actor_name text,
  actor_role_id integer,
  module text not null,
  action text not null,
  record_table text,
  record_id text,
  record_label text,
  summary text,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.activity_log enable row level security;

drop policy if exists activity_log_select_super_admin on public.activity_log;
create policy activity_log_select_super_admin
on public.activity_log
for select
to authenticated
using (app_private.is_super_admin());

-- No direct insert/update/delete policy is created in Phase 1.
-- Logging should later go through a safe RPC or trigger path.
grant select on public.activity_log to authenticated;

create index if not exists activity_log_created_at_idx
on public.activity_log (created_at desc);

create index if not exists activity_log_actor_old_user_id_idx
on public.activity_log (actor_old_user_id);

create index if not exists activity_log_module_idx
on public.activity_log (module);

create index if not exists activity_log_action_idx
on public.activity_log (action);

create index if not exists activity_log_record_idx
on public.activity_log (record_table, record_id);
