-- =====================================================================
-- PWA phone push subscriptions
-- - Stores browser Push API subscriptions per authenticated CRM user.
-- - No notification rows are changed; push delivery remains best-effort.
-- =====================================================================

create table if not exists public.push_subscriptions (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references public.users(id) on delete cascade,
  old_user_id    integer not null,
  endpoint       text not null unique,
  subscription   jsonb not null,
  user_agent     text,
  platform       text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  last_seen_at   timestamptz not null default now(),
  constraint push_subscriptions_subscription_object
    check (jsonb_typeof(subscription) = 'object')
);

create index if not exists idx_push_subscriptions_user
  on public.push_subscriptions (user_id);

create index if not exists idx_push_subscriptions_old_user
  on public.push_subscriptions (old_user_id);

alter table public.push_subscriptions enable row level security;

drop policy if exists push_subscriptions_own_select on public.push_subscriptions;
create policy push_subscriptions_own_select on public.push_subscriptions
  for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists push_subscriptions_own_insert on public.push_subscriptions;
create policy push_subscriptions_own_insert on public.push_subscriptions
  for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and exists (
      select 1
      from public.users u
      where u.id = (select auth.uid())
        and u.old_user_id = old_user_id
        and coalesce(u.status, 'Active') <> 'Inactive'
    )
  );

drop policy if exists push_subscriptions_own_update on public.push_subscriptions;
create policy push_subscriptions_own_update on public.push_subscriptions
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (
    user_id = (select auth.uid())
    and exists (
      select 1
      from public.users u
      where u.id = (select auth.uid())
        and u.old_user_id = old_user_id
        and coalesce(u.status, 'Active') <> 'Inactive'
    )
  );

drop policy if exists push_subscriptions_own_delete on public.push_subscriptions;
create policy push_subscriptions_own_delete on public.push_subscriptions
  for delete to authenticated
  using (user_id = (select auth.uid()));

grant select, insert, update, delete on public.push_subscriptions to authenticated;

do $$
begin
  if to_regclass('public.push_subscriptions_id_seq') is not null then
    grant usage, select on sequence public.push_subscriptions_id_seq to authenticated;
  end if;
end $$;

notify pgrst, 'reload schema';
