-- =====================================================================
-- Work Inbox / Record Discussion V1
-- - Adds lightweight, record-linked discussion threads.
-- - Does not alter existing ticket/task/lead/booking/calibration tables.
-- - Uses module-permission-aware RLS and existing public.users identities.
-- =====================================================================

create schema if not exists private;

create or replace function private.current_user_can_access_work_module(p_record_type text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with requested_module as (
    select case lower(coalesce(p_record_type, ''))
      when 'ticket' then 'tickets'
      when 'task' then 'tasks'
      when 'lead' then 'leads'
      when 'booking' then 'booking'
      when 'calibration' then 'calibration'
      else null
    end as module_name
  )
  select exists (
    select 1
    from public.users u
    cross join requested_module rm
    where u.id = (select auth.uid())
      and rm.module_name is not null
      and coalesce(u.status, 'Active') <> 'Inactive'
      and (
        u.role_id in (1, 99)
        or exists (
          select 1
          from public.module_permission mp
          where mp.role_id = u.role_id
            and mp.module = rm.module_name
            and mp.can_access is true
        )
      )
  );
$$;

revoke all on function private.current_user_can_access_work_module(text) from public;
grant usage on schema private to authenticated;
grant execute on function private.current_user_can_access_work_module(text) to authenticated;

create table if not exists public.work_threads (
  id                     bigint generated by default as identity primary key,
  record_type            text not null,
  record_id              text not null,
  title                  text,
  reference              text,
  company_name           text,
  created_by             uuid references public.users(id) on delete set null,
  created_by_old_user_id integer,
  is_archived            boolean not null default false,
  last_message_at        timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  constraint work_threads_record_type_check
    check (record_type in ('ticket', 'task', 'lead', 'booking', 'calibration')),
  constraint work_threads_record_unique unique (record_type, record_id)
);

create index if not exists idx_work_threads_record
  on public.work_threads (record_type, record_id);
create index if not exists idx_work_threads_recent
  on public.work_threads (coalesce(last_message_at, updated_at, created_at) desc);

create table if not exists public.work_messages (
  id                     bigint generated by default as identity primary key,
  thread_id              bigint not null references public.work_threads(id) on delete cascade,
  body                   text,
  attachment_paths       text[] not null default '{}'::text[],
  mentioned_old_user_ids integer[] not null default '{}'::integer[],
  created_by             uuid references public.users(id) on delete set null,
  created_by_old_user_id integer,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  constraint work_messages_content_check
    check (
      length(btrim(coalesce(body, ''))) > 0
      or coalesce(array_length(attachment_paths, 1), 0) > 0
    )
);

create index if not exists idx_work_messages_thread_created
  on public.work_messages (thread_id, created_at);
create index if not exists idx_work_messages_mentions
  on public.work_messages using gin (mentioned_old_user_ids);

create table if not exists public.work_thread_reads (
  thread_id        bigint not null references public.work_threads(id) on delete cascade,
  user_old_user_id integer not null,
  last_read_at     timestamptz not null default now(),
  primary key (thread_id, user_old_user_id)
);

create index if not exists idx_work_thread_reads_user
  on public.work_thread_reads (user_old_user_id, last_read_at desc);

create or replace function private.touch_work_thread_on_message()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  update public.work_threads
     set last_message_at = new.created_at,
         updated_at = now()
   where id = new.thread_id;
  return new;
end;
$$;

revoke all on function private.touch_work_thread_on_message() from public;

drop trigger if exists work_messages_touch_thread on public.work_messages;
create trigger work_messages_touch_thread
  after insert on public.work_messages
  for each row
  execute function private.touch_work_thread_on_message();

alter table public.work_threads enable row level security;
alter table public.work_messages enable row level security;
alter table public.work_thread_reads enable row level security;

drop policy if exists work_threads_staff_read on public.work_threads;
create policy work_threads_staff_read on public.work_threads
  for select to authenticated
  using ((select private.current_user_can_access_work_module(record_type)));

drop policy if exists work_threads_staff_insert on public.work_threads;
create policy work_threads_staff_insert on public.work_threads
  for insert to authenticated
  with check (
    (select private.current_user_can_access_work_module(record_type))
    and (created_by is null or created_by = (select auth.uid()))
  );

drop policy if exists work_threads_staff_update on public.work_threads;
create policy work_threads_staff_update on public.work_threads
  for update to authenticated
  using ((select private.current_user_can_access_work_module(record_type)))
  with check ((select private.current_user_can_access_work_module(record_type)));

drop policy if exists work_messages_staff_read on public.work_messages;
create policy work_messages_staff_read on public.work_messages
  for select to authenticated
  using (
    exists (
      select 1
      from public.work_threads wt
      where wt.id = thread_id
        and (select private.current_user_can_access_work_module(wt.record_type))
    )
  );

drop policy if exists work_messages_staff_insert on public.work_messages;
create policy work_messages_staff_insert on public.work_messages
  for insert to authenticated
  with check (
    (created_by is null or created_by = (select auth.uid()))
    and exists (
      select 1
      from public.work_threads wt
      where wt.id = thread_id
        and (select private.current_user_can_access_work_module(wt.record_type))
    )
  );

drop policy if exists work_thread_reads_own_all on public.work_thread_reads;
create policy work_thread_reads_own_all on public.work_thread_reads
  for all to authenticated
  using (
    exists (
      select 1
      from public.users u
      where u.id = (select auth.uid())
        and u.old_user_id = user_old_user_id
    )
  )
  with check (
    exists (
      select 1
      from public.users u
      where u.id = (select auth.uid())
        and u.old_user_id = user_old_user_id
    )
    and exists (
      select 1
      from public.work_threads wt
      where wt.id = thread_id
        and (select private.current_user_can_access_work_module(wt.record_type))
    )
  );

grant select, insert, update on public.work_threads to authenticated;
grant select, insert on public.work_messages to authenticated;
grant select, insert, update on public.work_thread_reads to authenticated;

do $$
begin
  if to_regclass('public.work_threads_id_seq') is not null then
    grant usage, select on sequence public.work_threads_id_seq to authenticated;
  end if;

  if to_regclass('public.work_messages_id_seq') is not null then
    grant usage, select on sequence public.work_messages_id_seq to authenticated;
  end if;
end $$;
